[workspace]
members = [
    "phalanx",
    "phalanx-common",
    "phalanx-discovery",
    "phalanx-dispatcher",
    "phalanx-index",
    "phalanx-overseer",
    "phalanx-proto",
    "phalanx-storage"
]
