[package]
name = "phalanx-manager"
version = "0.1.0"
authors = ["Minoru Osuka <minoru.osuka@gmail.com>"]
edition = "2018"

[[bin]]
name = "phalanx-overseer"
path = "src/main.rs"

[dependencies]
async-std = "1.6.1"
clap = "2.33.0"
futures-util = "0.3.5"
hyper = "0.13.5"
log = "0.4.8"
prometheus = "0.8.0"
tokio = { version = "0.2.21", features = [ "full" ] }

phalanx-common = { version = "0.1.0", path = "../phalanx-common" }
phalanx-discovery = { version = "0.1.0", path = "../phalanx-discovery" }
