[package]
name = "phalanx-common"
version = "0.1.0"
authors = ["Minoru Osuka <minoru.osuka@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.7.1"
tokio = { version = "0.2.21", features = [ "full" ] }
