[package]
name = "phalanx-proto"
version = "0.1.0-dev"
authors = ["Minoru Osuka <minoru.osuka@gmail.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
tonic-build = "0.3"

[dependencies]
num = "0.3"
prost = "0.6"
serde = "1.0"
tonic = "0.3"

[dev-dependencies]
serde_json = "1.0"
