[package]
name = "phalanx-proto"
version = "0.1.0"
authors = ["Minoru Osuka <minoru.osuka@gmail.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
tonic-build = "0.2.0"

[dependencies]
prost = "0.6.1"
tonic = "0.2.1"
